print("Band Name Generator Project")
print("What's the name of the city you grew up in?")
city = input()
print("What's your pet's name?")
pet = input()
length = len(city) + len(pet)
print("Your band name could be \"" + city + " " + pet + "(" + str(length) + ")\"")